name: Deployment (Container)
on:
  push:
    branches:
      - main
      - dev
env:
  CACHE_KEY: node-deps
  MONGODB_DB_NAME: gha-demo
jobs:
  test:
    # configured under repo/settings/environment=testing
    environment: testing
    # runs on a github-runner-machine
    # this machine just hosts the container declared below
    runs-on: ubuntu-latest
    # job runs now in container
    container: 
      # image names as per published images on docker hub portal
      image: node:16
      # env vars needed by the container image itself
      # env: 
    env:
      # external mongodb is not needed now
      #MONGODB_CONNECTION_PROTOCOL: mongodb+srv
      #MONGODB_CLUSTER_ADDRESS: cluster0.b2octig.mongodb.net
      #MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      #MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      # refers to the mongodb-service
      MONGODB_CONNECTION_PROTOCOL: mongodb
      MONGODB_CLUSTER_ADDRESS: mongodb-service
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: example
      PORT: 8080
    # deploy a mongodb service into the container
    services:
       mongodb-service:
        image: mongo
        env: 
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ env.CACHE_KEY }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT # requires MongoDB Atlas to accept requests from anywhere!
      - name: Run tests
        run: npm test
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        env:
          PORT: 3000
        run: |        
          echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
          echo "${{ env.PORT }}"
